server:
  port: 8080

spring:
  application:
    name: worknest-service

  datasource:
    url: jdbc:mysql://localhost:3306/platform_master?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  jackson:
    serialization:
      indent-output: true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

app:
  tenant:
    header: X-Tenant-ID
    default: master