package com.worknest.tenant.enums;

public enum AuditEntityType {
    EMPLOYEE,
    TEAM,
    PROJECT,
    TASK,
    LEAVE_REQUEST,
    ANNOUNCEMENT,
    ATTACHMENT,
    JOB_POSITION,
    CANDIDATE,
    CANDIDATE_APPLICATION,
    CANDIDATE_COMMENT,
    INTERVIEW,
    INTERVIEW_FEEDBACK,
    HR_MESSAGE,
    TEAM_CHAT,
    TEAM_CHAT_MESSAGE,
    NOTIFICATION
}
